CREATE TABLE formresults (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	xmlpath VARCHAR(255) NOT NULL,
	question BLOB NOT NULL,
	answer BLOB NOT NULL,
	date INT UNSIGNED NOT NULL,
	uid VARCHAR(36) NOT NULL,
	PRIMARY KEY id (id)
) TYPE = MyISAM COMMENT ='';

