CREATE TABLE formresults (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	xmlpath VARCHAR(255) NOT NULL,
	question VARCHAR(2560) NOT NULL,
	answer VARCHAR(2560) NOT NULL,
	date INT UNSIGNED NOT NULL,
	uid INT NOT NULL,
	PRIMARY KEY id (id)
) TYPE = MyISAM COMMENT ='';

